run-crank/cog-marketo

- test/steps/lead-create-or-update.ts
- test/steps/lead-delete.ts
Added unit tests for steps:
- lead-or-create-lead
- lead-delete
> Added cog-marketo unit tests

- src/steps/custom-object-delete.ts
- src/steps/custom-object-field-equals.ts
- Query filter type will always be linkField
- Dedupe Fields will be added to fields to be queried
- Value for checking field value to use `String()` instead of `.toString()` to be able to check null
* misclick on commit message, sorry bout that
> Change query and filter implementation of linked lead

- src/client/mixins/lead-aware.ts
- src/steps/lead-field-equals.ts
Note: this does not implement the `PUT` with `_method=GET` workaround to this issue mentioned [in Marketo's API docs](https://developers.marketo.com/rest-api/lead-database/leads/#query).  ...Because that workaround does not appear to actually work.
Instead, in cases where the request _would_ fail, we just return to the default, bare minimum field retrieval.
Closes #70
> Lead retrieval sanity checking on request size

- package-lock.json
- package.json
- src/steps/custom-object-field-equals.ts
- src/steps/lead-field-equals.ts
- test/steps/custom-object-field-equals.ts
- test/steps/lead-field-equals.ts
Added to `Lead` field check step and `Custom Object` field check step.
> Support "be one of" and "not be one of" operators

- src/steps/custom-object-field-equals.ts
- src/steps/lead-field-equals.ts
1. When Set Operator fails, an `(empty value)` string is displayed instead of nothing
this is because the `actualValue` is not being passed for when set operators are used.
2. For `Custom Objects`, The Set Operators evaluate `null` as passing instead of failing. This is due to `String(actualValue)` constructor calls that attempts to convert the value as string. The fix is to default first to `string empty` before converting to `String`. This is more explained in the image below:
> Marketo Set Operator Fixes

- package-lock.json
- package.json
- src/steps/custom-object-field-equals.ts
- src/steps/lead-field-equals.ts
1. An issue wherein sometimes `(empty value)` is displayed for failing Set Operator displays/messages
2. An issue wherein the `but it was set to <value>` message displays the `<value>` twice.
> Util update and display fixes

- src/client/mixins/lead-aware.ts
- src/steps/check-lead-activity.ts
- src/steps/custom-object-create-or-update.ts
- src/steps/custom-object-delete.ts
- src/steps/custom-object-field-equals.ts
- src/steps/lead-delete.ts
- src/steps/lead-field-equals.ts
- src/steps/smart-campaign-add-lead.ts
- test/client/client-wrapper.ts
- test/steps/lead-delete.ts
- test/steps/lead-field-equals.ts
- test/steps/smart-campaign-add-lead.ts
It is possible for Marketo to be configured (by Marketo support) such that the lead's email address is no longer a unique key on the lead table (meaning, there may be more than one lead record per email address).  In this case, Marketo Support configures a custom uniqueness constraint, which is commonly a composite key of email + partition ID.
In order to handle this (relatively uncommon) case, this PR adds an optional `partitionId` field to all affected steps.
Note: the lead create step is unaffected, as it's already possible to specify the partition ID in the lead object definition.
> Feature: support duplicated leads (on email) by partition

- src/client/mixins/lead-aware.ts
What's Changed:
* Ensured that only fields with rest are being included in Marketo query
This causes a weird error for instances that has fields that don't have `field.rest` property.
> Ensured that only fields with rest are being included in Marketo query

- src/client/client-wrapper.ts
- src/client/mixins/index.ts
- src/client/mixins/stats-aware.ts
- src/steps/check-api-usage.ts
- test/client/client-wrapper.ts
- test/steps/check-api-usage.ts
Added a new step to check daily Marketo API usage against the organization's daily limit of API calls.  If a user omits the daily limit field, then it is defaulted to a daily limit of 50,000 calls.
This pull requests includes:
1.  check-api-usage step
2.  stats-aware mixin in the client wrapper
3.  tests for the new step and client wrapper
> added check-api-usage step and tests

- src/steps/check-api-usage.ts
I changed the success message for the API usage step to include % usage.
> Changed message for check-api-usage step

- src/client/mixins/stats-aware.ts
- src/steps/check-api-usage.ts
- test/client/client-wrapper.ts
- test/steps/check-api-usage.ts
Added getWeeklyApiUsage() to the client wrapper and added a comparison to the message for the the checkApiUsage step.
> Added weekly API usage

- .circleci/config.yml
- examples/caching-example-1.yml
- examples/caching-example-2.yml
- examples/caching-example-3.yml
- package-lock.json
- package.json
- src/client/caching-client-wrapper.ts
- src/client/mixins/custom-object-aware.ts
- src/client/mixins/lead-aware.ts
- src/core/cog.ts
- src/core/grpc-server.ts
- src/steps/custom-object-create-or-update.ts
- src/steps/custom-object-delete.ts
- src/steps/custom-object-field-equals.ts
- src/steps/lead-delete.ts
- test/client/caching-client-wrapper.ts
- test/client/client-wrapper.ts
- test/core/cog.ts
Added a caching-client-wrapper proxy that wraps the original client-wrapper. This will check the Redis cache for leads, smart-campaigns, and custom objects before making the API call to Marketo.
Caching is limited to Marketo:
1. Leads
2. Custom Objects
3. Campaigns
Marketo activities have not been cached at this time.
> Implement Caching for Marketo Cog

- src/core/cog.ts
- test/core/cog.ts
Before, a faulty redisUrl would crash the Cog.
This update will handle a faulty redisUrl by bypassing the caching-client-wrapper and going straight to the client-wrapper.
> Bypass redis with faulty url

- src/client/caching-client-wrapper.ts
- src/client/mixins/lead-aware.ts
- src/steps/associate-web-activity.ts
- test/steps/associate-web-activity.ts
New Associate Web Activity Step accepts a _mkto_trk cookie and associates it with a Marketo lead by email.
> Associate Web Activity Step

- package-lock.json
- package.json
- src/core/base-step.ts
- src/steps/bulk-lead-field-equals.ts
- src/steps/custom-object-field-equals.ts
- src/steps/lead-by-id-field-equals.ts
- src/steps/lead-field-equals.ts
- src/steps/program-members/program-member-field-equals.ts
- src/steps/programs/program-field-equals.ts
- Update typescript cog utilities
- Some step messages will have PII removed if a "__piiSuppressionLevel" is passed in the stepData
> PII suppression in step messages

- src/client/mixins/activity-aware.ts
- src/client/mixins/lead-aware.ts
- src/steps/bulk-lead-create-or-update.ts
- src/steps/check-lead-activity.ts
- src/steps/lead-field-equals.ts
- test/steps/check-lead-activity.ts
- test/steps/lead-field-equals.ts
added bulk functionality to check lead activity step
added tests for new bulk functionality on check field equals and check lead activity steps
fixed update lead step bug where email needed to be an update field in order to go through
adjusted the bulk create/update step records to return passedLeads rather than createdLeads and updatedLeads
> Check Lead Activity Step: Added bulk functionality | Other Marketo Fixes

- src/steps/bulk-lead-create-or-update.ts
Fixed step record message as it was referencing 2 variables when only one was provided.
> Bulk Create/Update step: fixed pass message on step record

- src/client/mixins/lead-aware.ts
moved mustHaveFields into each function that uses it, since the 'this' object being referenced is actually the client wrapper, not the LeadAwareMixin, so it wasn't being referenced properly.
> Bug Fix: must have fields not always being returned

- src/steps/check-lead-activity-by-id.ts
- test/steps/check-lead-activity-by-id.ts
Needed to be checking the length of the returned array to see if any activities were present, rather than just checking that the array exists.
> Bug Fix: Check Marketo Lead Activity By ID Step

- package.json
- src/client/caching-client-wrapper.ts
- src/client/client-wrapper.ts
- src/client/mixins/lead-aware.ts
- src/client/mixins/smart-campaign-aware.ts
- src/core/base-step.ts
- src/core/cog.ts
- src/steps/check-lead-activity.ts
- src/steps/lead-field-equals.ts
- src/steps/program-members/program-member-add-or-remove.ts
- src/steps/smart-campaign-add-lead.ts
- src/steps/static-lists/static-list-add-lead.ts
- test/client/caching-client-wrapper.ts
- test/steps/program-members/program-member-add-or-remove.ts
- test/steps/smart-campaign-add-lead.ts
- test/steps/static-lists/static-list-add-lead.ts
Includes bulk functionality for these steps:
- add or remove marketo program member (new step that accepts an email or id, or bulk tokens of either)
- add leads to static list (accepts existing comma separated list of ids, or bulk token with ids)
- add lead to smart campaign (accepts email or id, or bulk tokens of either)
Also includes tests for new functionality, as well as a new bulkSupport property on the Field interface, to keep track of which fields can accept a bulk token.
> New bulk steps

- src/steps/lead-field-equals.ts
- src/steps/program-members/program-member-add-or-remove.ts
- test/steps/lead-field-equals.ts
- LeadFieldEquals step: adjusted bulk logic to handle IDs as well as emails (bug 6278)
- AddOrRemoveProgramMember step: fixed issue where step message wasn't being sent back properly (bug 6291)
- Added new tests for leadFieldEquals step
> Bulk step fixes

- .circleci/config.yml
- Dockerfile
- README.md
- package.json
- src/client/mixins/lead-aware.ts
- test/core/cog.ts
- In findLeadByEmail and findLeadByField methods: Changed max length of characters in the fieldList to be 7000 before we break the fields into chunks. When the length is larger than 7k then we will break the api calls into chunks of 200 fields max. This will prevent Marketo from returning and error with status 500 "Unknown Marketo error."
- Updated dockerhub repo to stackmoxie/marketo
> Changed dockerhub repo and adjusted max field length for api calls

- src/steps/check-lead-activity-by-id.ts
- src/steps/check-lead-activity.ts
- src/steps/smart-campaign-add-lead.ts
- test/steps/check-lead-activity-by-id.ts
- Fixed an error where the findLeadByField method was successfully returning a lead object, but the object is empty. The steps were returning a generic ERROR state, but now they will return a FAILED state with a message that we could not find the lead.
- Fixed the "Activity Type not found" test
> Handle case where findLeadByField method returns an empty object
