run-crank/cog-marketo

scenarios/FormTestValidatedinMarketo.yml
scenarios/MarketoAPITest.yml

Added Marketo Test scenarios
- Marketo Form Test
- Marketo API Test

Add UAT/Example Scenarios

---

src/client/client-wrapper.ts
src/client/mixins/lead-aware.ts

1. Created `mixin` for lead to free up `client-wrapper`

Created mixins

---

src/client/client-wrapper.ts
src/client/mixins/index.ts
src/client/mixins/smart-campaign-aware.ts
src/steps/smart-campaign-add-lead.ts
test/steps/smart-campaign-add-lead.ts
tslint.json

- can now add lead to smart campaign via lead email and campaign id/name
- unit tested

Implemented adding of marketo lead to smart campaign

---

src/steps/smart-campaign-add-lead.ts
test/steps/smart-campaign-add-lead.ts

- removed previous implementation of error handler for said error
- updated unit test
- changed string display for field requirements

handled trigger campaign error

---

src/client/mixins/smart-campaign-aware.ts
src/steps/smart-campaign-add-lead.ts
test/client/client-wrapper.ts

updated unit tests related to smart campaign in client wrapper

updated client wrapper unit test

---

src/client/client-wrapper.ts
src/client/mixins/activity-aware.ts
src/client/mixins/index.ts
src/steps/check-lead-activity.ts
test/scenarios/check-lead-activity.crank.yml
test/scenarios/marketo-api-test.crank.yml

I am requesting for review for feature #18 
- Unit tests are not yet in place

[WIP] Initial Commit for Check Lead Activity Step

---

test/steps/check-lead-activity.ts

Added tests for check-lead-activity step

---

src/client/client-wrapper.ts
src/client/mixins/custom-object-aware.ts
src/client/mixins/index.ts
src/steps/custom-object-create-or-update.ts
src/steps/custom-object-delete.ts

Initial Implementation of create and delete custom object

---

src/steps/custom-object-delete.ts
src/steps/custom-object-field-equals.ts

initial implementation of custom object field validation

---

package-lock.json
package.json
src/client/mixins/custom-object-aware.ts
src/client/mixins/lead-aware.ts
src/steps/custom-object-create-or-update.ts
src/steps/custom-object-delete.ts
src/steps/custom-object-field-equals.ts
test/client/client-wrapper.ts
test/steps/custom-object-create-or-update.ts
test/steps/custom-object-delete.ts
test/steps/custom-object-field-equals.ts

- included describe field checker to get api names of fields which have display names as values
- update unit tests

temp fix for marketo bug on link field value

---

src/steps/custom-object-create-or-update.ts
src/steps/custom-object-delete.ts
src/steps/custom-object-field-equals.ts
test/steps/custom-object-create-or-update.ts
test/steps/custom-object-delete.ts
test/steps/custom-object-field-equals.ts

- added handling for dedupeFields
- added success and reason checker after api calls
- fixed type messages
- updated unit tests

added dedupeField Handling for delete and field validation

---

src/steps/custom-object-create-or-update.ts
test/steps/custom-object-create-or-update.ts

change field name object to customObject

---

src/steps/custom-object-create-or-update.ts
src/steps/custom-object-delete.ts
src/steps/custom-object-field-equals.ts

Added checker if linkfield of lead is null and checker if linkfield exists for custom object

---

src/steps/custom-object-create-or-update.ts

Clearly indicate whether custom objects is created or updated

---

src/steps/custom-object-delete.ts

Fixed wrong custom object being deleted bug

---

test/scenarios/Custom Object/Custom Object -  One-To-Many Object field.crank.yml
test/scenarios/Custom Object/Custom Object - Link By Email field.crank.yml
test/scenarios/Custom Object/Custom Object - Multiple dedupe fields.crank.yml
test/scenarios/Custom Object/Custom Object - QA Alternative Link Field Object.yml
test/scenarios/Operators/Form Test with Operators.crank.yml
test/scenarios/Operators/Lead API Test with Operators.crank.yml
test/scenarios/Operators/Smart Campaign with Operators.crank.yml

Added new scenarios for Marketo Custom Objects and the Operatos

Marketo Custom Object & Operators Scenarios

---

Dockerfile
package-lock.json
package.json
src/steps/custom-object-field-equals.ts
src/steps/lead-field-equals.ts
test/steps/custom-object-field-equals.ts
test/steps/lead-field-equals.ts

Implemented `be set` and `not be set` operators for `Marketo` `Lead` and `Custom Object`.

Set Operators Implementation

---

Dockerfile
package-lock.json
package.json

- Fixes confusing error message when using "not set" operator
- Resolves underlying dependency vulnerabilities
- Rolls back Dockerfile change that could result in unnecessarily large images

Fix dependency-related bugs

---

package-lock.json
package.json
src/core/base-step.ts
src/steps/custom-object-field-equals.ts
src/steps/lead-field-equals.ts

Leveraged the assert function of utilities package

Leveraged the assert function of utilities package

---

src/steps/check-lead-activity.ts
src/steps/custom-object-create-or-update.ts
src/steps/custom-object-delete.ts
src/steps/custom-object-field-equals.ts
src/steps/lead-field-equals.ts

Some messages that are an `Error` have been changed to `Fail`

Fail and error message changes

---

src/steps/smart-campaign-add-lead.ts

for testing purposes to rerun code climate

added string type to email

---

src/client/caching-client-wrapper.ts
src/client/client-wrapper.ts
src/client/mixins/email-aware.ts
src/steps/send-sample-email.ts
test/steps/send-sample-email.ts

Sends a sample email from Marketo to the recipient's email address.

Send Sample Email Step

---

src/client/caching-client-wrapper.ts
src/client/mixins/lead-aware.ts
src/steps/lead-merge.ts
test/client/caching-client-wrapper.ts
test/client/client-wrapper.ts
test/steps/lead-merge.ts

New step and tests added. This step will merge two Marketo Leads.

Merge Leads Step

---

src/steps/lead-discover.ts
test/steps/lead-discover.ts

Added discover lead step and test

added discover lead step

---

src/steps/bulk-lead-create-or-update.ts

bulk create or update step now accepts raw csv data and will return original version of all failed rows

List Import Error Handling 

---

src/client/mixins/lead-aware.ts

fixed bug where leads were not found if a specific partition was provided.

fixed partition bug

---

src/steps/check-lead-activity-by-id.ts
src/steps/check-lead-activity.ts

Adjusted this method for comparing expected and actual attributes in both the check lead activity and check lead activity by ID steps.

Adjusted hasMatchingAttribute method

---

src/steps/program-members/bulk-program-member-add-or-remove.ts

Fixed actions for BulkAddOrRemoveProgramMemberStep

Changed actions for BulkAddOrRemoveProgramMemberStep

---

src/steps/lead-merge.ts

Added 'update' to the actionList for the merge leads step

Merge Leads step actionList update

---

src/steps/static-lists/static-list-add-lead.ts
src/steps/static-lists/static-list-member-count.ts
src/steps/static-lists/static-list-remove-lead.ts
test/steps/static-lists/static-list-add-lead.ts
test/steps/static-lists/static-list-remove-lead.ts

-Added optional programId field to filter multiple static lists
-Updated tests

Added optional programId field to static list steps to filter

---

src/steps/program-members/bulk-program-member-add-or-remove.ts
src/steps/program-members/program-member-add-or-remove.ts
test/steps/program-members/bulk-program-member-add-or-remove.ts
test/steps/program-members/program-member-add-or-remove.ts

-Add or remove program members by program name or id

Add program members by program name or id
